[install.scopes]
"@frmscoe" = {url="https://npm.pkg.github.com/:_authToken=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"}
[test]
preload = ["./__tests__/__mocks__/arango.js", "./__tests__/__mocks__/ioredis.js"]
